services:
  # Backend API
  - type: web
    name: doublefeature-backend
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TMDB_API_KEY
        sync: false
      - key: REACT_APP_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    rootDir: backend

  # Frontend
  - type: web
    name: doublefeature-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: VITE_BACKEND_URL
        value: https://doublefeature-backend.onrender.com
      - key: NODE_ENV
        value: production
    rootDir: frontend
